// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
	Role     int    `form:"role"`
}

type UserLoginResp struct {
	Respone
	Data map[string]string `json:"data,default="" "`
}

type UserRigisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserRigisterResp struct {
	Respone
}

type UpdateRoleReq struct {
	Id   string `json:"id"`
	Role int    `json:"role"`
}

type UpdateRoleResp struct {
	Respone
}

type UpdatePasswordReq struct {
	Password string `json:"password"`
}

type UpdatePasswordResp struct {
	Respone
}

type Respone struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
